//
// Created by nemesis on 15/06/21.
//

#ifndef CATAPULT_SERVER_ACCOUNTLINKBASETRANSACTION_H
#define CATAPULT_SERVER_ACCOUNTLINKBASETRANSACTION_H

class AccountLinkBaseTransaction {};

#endif // CATAPULT_SERVER_ACCOUNTLINKBASETRANSACTION_H
