pipeline {
	agent {
        label 'catapult-build-node'
    }

    // using the Timestamper plugin we can add timestamps to the console log
    options {
        timestamps()
    }

    environment {
        DOCKER_REGISTRY = "249767383774.dkr.ecr.ap-southeast-1.amazonaws.com"
        CREDENTIAL_ID = "ecr:ap-southeast-1:jenkins-ecr"
        IMAGE = "proximax-catapult-server"
        BUILD_IMAGE = "proximax-catapult-server-dependencies-build-image:v1.0-buster"
    }

	stages {
		stage ('Build') {
            steps {
                echo 'Building catapult-server inside a docker'
                script {
                    def buildImage = docker.image("${BUILD_IMAGE}")
                    docker.withRegistry("https://${DOCKER_REGISTRY}", "${CREDENTIAL_ID}"){
                        buildImage.inside {
                            sh """
                                echo 'Building catapult-server'
                                rm -rf _build
                                mkdir _build 
                                cd _build
                                cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-pthread" .. 
                                make publish 
                                make \
                                catapult.mongo.plugins.accountlink \
                                catapult.mongo.plugins.aggregate \
                                catapult.mongo.plugins.config \
                                catapult.mongo.plugins.contract \
                                catapult.mongo.plugins.exchange \
                                catapult.mongo.plugins.lockhash \
                                catapult.mongo.plugins.locksecret \
                                catapult.mongo.plugins.metadata \
                                catapult.mongo.plugins.mosaic \
                                catapult.mongo.plugins.multisig \
                                catapult.mongo.plugins.namespace \
                                catapult.mongo.plugins.property \
                                catapult.mongo.plugins.transfer \
                                catapult.mongo.plugins.upgrade \
                                catapult.mongo.plugins.service \
                                catapult.plugins.accountlink \
                                catapult.plugins.aggregate \
                                catapult.plugins.config \
                                catapult.plugins.contract \
                                catapult.plugins.exchange \
                                catapult.plugins.hashcache \
                                catapult.plugins.hashcache.cache \
                                catapult.plugins.lockhash \
                                catapult.plugins.locksecret \
                                catapult.plugins.metadata \
                                catapult.plugins.mosaic \
                                catapult.plugins.multisig \
                                catapult.plugins.namespace \
                                catapult.plugins.property \
                                catapult.plugins.signature \
                                catapult.plugins.transfer \
                                catapult.plugins.upgrade \
                                catapult.plugins.service \
                                extension.addressextraction \
                                extension.diagnostics \
                                extension.eventsource \
                                extension.filespooling \
                                extension.harvesting \
                                extension.hashcache \
                                extension.mongo \
                                extension.networkheight \
                                extension.nodediscovery \
                                extension.packetserver \
                                extension.partialtransaction \
                                extension.pluginhandlers \
                                extension.sync \
                                extension.syncsource \
                                extension.timesync \
                                extension.transactionsink \
                                extension.unbondedpruning \
                                extension.zeromq \
                                sirius.bc \
                                catapult.broker \
                                catapult.recovery \
                                catapult.tools.address \
                                catapult.tools.benchmark \
                                catapult.tools.health \
                                catapult.tools.nemgen \
                                catapult.tools.nemgen.blockhashes \
                                catapult.tools.network \
                                catapult.tools.statusgen \
                                -j4
                                cd ..
                                ./scripts/release-script/copyDeps.sh _build/bin/ ./deps
                            """    
                        }
                    }
                    archiveArtifacts "_build/bin/*"
                }
            }
		}
        stage('Publish Image') {
            steps {
                echo 'Publish Image'
                script {
                    def newImage = docker.build("${IMAGE}","-f ./ci/debian/Dockerfile .")
                    docker.withRegistry("https://${DOCKER_REGISTRY}", "${CREDENTIAL_ID}"){
                        newImage.push("debian-build-${env.BUILD_NUMBER}") // also push using Jenkins build number
                    }
                }
            }
        }
    }
}